### ISSUE TITLE
Matplotlib tile allows me to drag the draw_plot section so low that the render content is inaccessible.

### ISSUE THREAD

**Issue by AkivaSherin** [bsherin/tactic#1038]
If I click on the handle to drag down the divider between the two sections, as long as I continue to click I can drag the divider even when my cursor is below the browser window. I have attached a video to show the issue. It can be resolved by refreshing.

https://user-images.githubusercontent.com/29513111/129806581-18e44555-290d-4040-a9b1-0e6075f16e78.mp4

**Comment by bsherin** [comment]
This is fixed. Was an issue generally with resizing layouts.
