### ISSUE TITLE
Make good tile templates

### ISSUE THREAD

**Issue by bsherin** [bsherin/tactic#169]
The default one can be minimal
Also make one that has just about everything in it with documentation

**Comment by bsherin** [comment]
Done

**Comment by arthurhjorth** [comment]
:+1: :rainbow: :smile: :balloon:   Is there a commit for this? Or where are the new templates?  :+1: :rainbow: :smile: :balloon:

**Comment by bsherin** [comment]
The "new" button that you use to create tiles now gives you s dropdown list with a few different templates to choose one. There's some chance you'll have to clear your browser cache to see it.

**Comment by arthurhjorth** [comment]
Ooooh, that is very cool! Thanks!
