### ISSUE TITLE
Tile Option: Multiple Answers?

### ISSUE THREAD

**Issue by arthurhjorth** [bsherin/tactic#183]
Maybe I've missed something but I don't see any way to give multiple answers options in Tiles. It's currently possible to fake it with:

```
    @property
    def options(self):
        options = [{"name": "test", "type": "text"}]
        for col_name in colum_names:
            options = options + [{"name" : col_name, "type": "boolean"}]
        return options
```

but I wonder if it's a general enough use case that it should be a core Tile option that accepts a list of names/strings/options?

**Comment by bsherin** [comment]
I was actually just wondering about this same thing. My use case is that I have data in which there is a column called "section" that labels each row in the data according to the section of the interview in which the row occurred. For some analyses I want to include some sections and not others. And what I want is a bunch of checkboxes.

But we are already up to 12 types of tile options. Maybe that's okay, or maybe the whole set should be rationalized. 

Another case that came up recently is floats. For now I decided to just have users input them as strings. But maybe they should be a special type of their own?

**Comment by arthurhjorth** [comment]
At the risk of hijacking this issue:

I think there's potential for users being confused by the mix of data types, user-data, and functions in Tile Options. There are currently seven "<blahblah>_select" options; some of them relate to features of the collection (columns, documents); some are essentially functions (palette, tokenizer, weight_function); some are data selectors (list, pipes); but all of these could be built easily by a user with the custom_list option, if there were a good API to all these things. (I know there already is for cols, and docs - I don't know about the rest.)

I *think* that I think it would be best to only offer basic widget-creation in Tile Options, and then let people figure out how to build them from there (giving easy access via API to palettes, tokenizers, etc.). E.g.

```
options = [{"name": "Palette", "type": "custom_list", "special_list" : user.get_available_palettes()}] 
```

I can see good arguments for letting them be core types rather than "hiding" them in the API. But if there are going to be Tile options for every single kind of list and data that we might decide to include down the road, it's hard to see where it ends.

**Comment by bsherin** [comment]
This where I'm leaning too. But there might be a couple of option types that we want to keep as special cases just because they're so common. For example, just about every tile has a couple of column selectors.

**Comment by arthurhjorth** [comment]
I totally agree with everything!

**Comment by bsherin** [comment]
The addition of code resources fixed a lot of this.
