### ISSUE TITLE
"Orphaned" analysis data

### ISSUE THREAD

**Issue by arthurhjorth** [bsherin/tactic#191]
There's one thing that keeps coming back to me as slightly problematic about the current implementation of the Tile-approach: analysis data in the spreadsheet can end up being orphaned, and we won't have any way of knowing where the data came from. 

For instance, take a clustering tile. Run it with 5 clusters, and add the cluster IDs to a new column. Run it again with 4 clusters for comparison and add them to a new column. Run it gain with 4 clusters, but with a new stoplist or porter (or some other small change). At this point you'll have three columns, all with different numbers, but unless you give them meaningful (and VERY long) names, you'll have no idea what is what.

An even bigger problem (I think) is that it makes data exploration difficult. If you don't remember the exact Tile settings that you used, you won't be able to replicate them and make minor modifications to see how/if that would change your clustering, or whatever analysis you're running. And to me, ease of exploring is one of the potentially cool uses of this system (and of computational methods in general).

One solution would be that Tiles produce a copy of themselves when they run (on `render_content()`), and that this Tile object is attached to the column somehow. That way, you can always open a column's tile to see what created the data, and you can change values. If it is a full-fledged tile, you can even easily just add data to a new column for comparison. Of course, if people manually change their values, things can get funny. But maybe Tiles can (optionally) lock the contents of "their" column to at least prevent accidental edits. Another potential downside is that you'll end up with a lot of Tile instances. Although maybe that's not a downside, but a feature?

Another solution would be to save all the metadata in a Tile. This would probably be the easier implementation of the two. Maybe if there's an easy way of copying this data into a new Tile, it would have most of the functionality of the Col + Tile option in terms of exploration. But if someone were to make changes to their Tile class in between saving the meta data and restoring a Tile from it, it might make things weird. Or it definitely will, but I guess there are ways of handling that.

**Comment by bsherin** [comment]
Yeah, this is kind of a side-effect of the way the whole thing is conceptualized. My idea for this was to implement what I've been calling, in my head, "lab notebook-like functionality." 

https://github.com/bsherin/tactic/issues/153

The idea is that there would be a notebook, that you can hide or show, associated with a project. When you show it, it would come down form the top or in from the side, and hide just part of the screen. You can just type notes there. Also there would be ways of squirting specific kinds of information there, such as "frozen" tiles, which would be tiles with their current html and settings.

This requires the user to actively store notes. But we can make the adding of stuff to the notebook a part of the tile API. So you can create a tile that saves its state there or write other information.

Thoughts?

**Comment by arthurhjorth** [comment]
My problem is that the system's _default_ behavior is not to link analysis with analysis-metadata.

Although I like all the features that you suggest in #153 I am honestly not sure that I would use the notebook. I've been working kinda hard to get all my thoughts and notes together in one place, and I've finally more or less succeeded (hooray, Evernote + xml export for [pretend] future-proofing.) I'd really rather not have another place to write my thoughts, "lab notes", etc.

For that reason I think that tying _functional_ aspects of Tactic in with more research-management'y aspects of _using_ Tactic might scare people like me from using it, or at least make certain aspects of it less enjoyable. Alternatively, if the UX of using the 'notebook' feature as a way saving/restoring/modifying frozen tiles + data is (more or less) seamless, maybe it doesn't matter that that is what is happening behind the scenes? But I would definitely prefer not to actually have to deal with a notebook.

This makes me realize: there should be a text-version of a log of what a user does, for easy record keeping. Is there one already? (opened #192)

**Comment by bsherin** [comment]
The notebook functionality is there now and pretty robust. And you can send tile settings to the notebook etc. I think that's as good as we're going to do on this for a while.
