### ISSUE TITLE
TileAPI: Things to put in a log

### ISSUE THREAD

**Issue by arthurhjorth** [bsherin/tactic#192]
Maybe this should be two separate issues, but I think it would be nice with a log. I feel like I often just try it out a bunch of different things in rapid succession, and I sometimes/often/mostly forgot what I did. But it's often interesting to think about my trajectory through an analysis.

Additionally/relatedly, would it be possible to add features to a Tile that specifies things to put in a text log? For instance, it might be nice to know what clustering configurations I ran on which column. But I might want to add more information that is particular to a Tile, or to the particular kind of analysis that it does.

**Comment by bsherin** [comment]
This exists now. See the new handle_tile_log mechanism

https://github.com/bsherin/tactic/wiki/Tile-Structure
