### ISSUE TITLE
Tile examples fail (have `,` at end of options dict)

### ISSUE THREAD

**Issue by arthurhjorth** [bsherin/tactic#198]
I think you accidentally left in the `,` at the end of the last option in the `options` dictionary. (Or maybe you left them in for pedagogical reasons?) Either, as they are, they don't compile when you load them.

**Comment by bsherin** [comment]
I fixed it. Let me know if you want the ability to modify the repository.

**Comment by arthurhjorth** [comment]
Great! And that would be nice, actually. Unless they're tiny changes like this, I'll put them in PRs and let your check/merge any changes I might make.

(And sorry, didn't read through my github notifications until now.)
