### ISSUE TITLE
Second part of the API: Commands available to a Tile

### ISSUE THREAD

**Issue by bsherin** [bsherin/tactic#34]
This is the second part of the Tile API. These are the commands that we want to make available to programmers of new tiles. There's still a lot to figure out here.

Note that all of these need to be accessed from within a tile using self.function(). The reason is that each tile has information about which table it is attached to. Keep in mind that a user might have multiple windows open and that there may be many users using the server at once.

## Basic data access and setting

------------------

    TileBase.get_document_names()

Returns a list of all document names in the current collection.

------------------

    TileBase.get_column_names(document_name) 

Returns a list containing the column names of the specified document.

------------------

    TileBase.get_number_rows(document_name) 

Returns the number of rows in the specified document.

------------------

    TileBase.get_row(document_name, row_number) 

Returns the specified row as a dict.

------------------

    TileBase.get_cell(document_name, row_number, column_name) 
    
Returns the text in the specified cell.

------------------

    TileBase.get_column_data(column_name, document_name) 
    
Get all contents of a column as a list. If document_name is not provided or is None then the content of the column from all documents is returned as one long list.

------------------
    TileBase.get_column_data_dict(column_name) 

Gets a dictionary indexed by document name, where the values are the rows of data in the document.

------------------

    TileBase.set_cell(document_name, row_number, column_name, text, cellchange=True) 
    
Sets the text in the specified cell. By default generates a CellChange event.

------------------

    TileBase.set_row(document_name, row_number, row_dictionary, cellchange=True) 
    
Sets the cells in the row using corresponding entries in the row\_dictionary. The row\_dictionary should have keys that correspond to column names. If some column names don't appear in the dictionary then nothing is done to those columns. By default, generates a CellChange event for each change.

------------------

    TileBase.set_column_data(document_name, column_name, data_list, cellchange=False) 
    
Sets the entire column in a document using the list. Note that, by default, no CellChange events are generated.

------------------

## Filtering and iteration

    TileBase.get_matching_rows(filter_function, document_name)

Returns a list of the matching rows. filter\_function should take a dict (corresponding to a row) as an argument, and should output a boolean. If document_name is missing or None then this will look across all documents in the collection.

------------------

    TileBase.display_matching_rows(filter_function, document_name)
    
Will cause the table to only display rows matching the filter_function. If document_name is missing or None then this will apply to all documents in the collection.

------------------

    TileBase.display_all_rows()
   
Will cause the table to display all rows.

------------------

    TileBase.apply_to_rows(func, document_name)
 
Applies the specified func to each row. func should expect a dict corresponding to the row as an input and it should return a dict corresponding to the modified row as output. If document_name is missing or None then this will apply to all documents in the collection.

------------------

## Other

------------------

    TileBase.get_selected_text()
    
Returns the text currently highlighted by the user

------------------

    TileBase.display_message(message_string)

Displays a status message somewhere on the screen. The idea is that this will be useful for debuggin tiles.

------------------

    TileBase.get_user_list(list_name)
    TileBase.get_tokenizer(tokenizer_name)
    TileBase.get_pipe_value(pipe_name)
    TileBase.get_weight_function(weight_function_name)

When a tile includes a list, tokenizer, pipe, or weight_function as one of the options that appears on the back of a tile, then update_options places the name of the relevant resource in the attribute made available to the tile. These commands make return the object associated with the name.

------------------

    TileBase.start_spinner()
    TileBase.stop_spinner()

These start and stop the spinning animation on the tile.

------------------

    TileBase.refresh_tile_now(new_html=None)

Updates the front of the tile using the passed html. If new_html is None then render_content is called to generate the html to be displayed.

-------------------

    TileBase.spin_and_refresh()

Starts the spinner, refreshes the tile, then stops the spinner.

-------------------

## Other parts of the namespace

Currently nltk, numpy, and matplotlib are in the namespace and available to tiles. I think ultimately we will want a lot more. We are going to need to think what sorts of analysis and visualization libraries we want to make available to tiles. Right now there are a few of my own modules loaded. But this needs to be thought about.

We're also going to want some unique capabilities, such as the ability to highlight text in the table in different colors. This might require some special colormap facilities.

## Still more questions

We're probably going to want to make it easy for the user to tokenize all text in a column, to apply a stop_list. More generally, we'll want some good classes for managing vocabularies. Right now my standard Vocabulary class is there. We might want to use that. Alternatively we might decide that nltk's frequency distribution tools are all that is needed.

Another big question: Do we want a tile to be able to create an entirely new document? Seems like there's no reason not to allow this. This would be one way that a tile could re-chunkify the data.

We might also want to facility re-chunkifying in other ways.

Special functions for managing timecodes.

Right now the system treats every cell as if it just contains text. It's up to the tile programmer to treat cells differently. Do we want to make it possible to attach types to columns?

**Comment by arthurhjorth** [comment]
I'll go through the open questions and open up an issue for each of them so that we can keep the discussions separate, if you don't mind. (In fact, I'll just go ahead and do it, and we can move them back here if you prefer.)

**Comment by arthurhjorth** [comment]
> Another big question: Do we want a tile to be able to create an entirely new document? Seems like there's no reason not to allow this. This would be one way that a tile could re-chunkify the data.
> We might also want to facility re-chunkifying in other ways.

Discussion here: #36

**Comment by arthurhjorth** [comment]
>Right now the system treats every cell as if it just contains text. It's up to the tile programmer to treat cells differently. Do we want to make it possible to attach types to columns?

Discussion here: #37

**Comment by arthurhjorth** [comment]
>We're probably going to want to make it easy for the user to tokenize all text in a column, to apply a stop_list.

Discussion here: #38

**Comment by bsherin** [comment]
The more updated version of this is now in the documentation viewer.
