### ISSUE TITLE
Allowing changes to text

### ISSUE THREAD

**Issue by arthurhjorth** [bsherin/tactic#38]
>We're probably going to want to make it easy for the user to tokenize all text in a column, to apply a stop_list. 

In the same vein as my response to whether we should allow chunking and allow tiles to create new documents: my personal take is that we shouldn't allow changes to the original text data. As soon as we do, we risk invalidating some of the data in the other columns. I think my suggestion would be to not change the text but instead create a new column (or document) with a tokenized text. That way, the original text is always preserved, and the data that we are actually doing the analysis on is explicit and visible.

**Comment by bsherin** [comment]
I meant here just that it should be easy to tokenize all text in a column in order to work on it within a tile, not modify the original data or even necessarily write it back to the table in any way.
